# Generated by Django 5.2.7 on 2025-11-02 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmostraSangue',
            fields=[
                ('id_amostra', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_sang', models.CharField(max_length=3)),
                ('quantidade_ml', models.PositiveIntegerField()),
                ('validade', models.DateField()),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('utilizada', 'Utilizada'), ('expirada', 'Expirada'), ('reservada', 'Reservada')], default='disponivel', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Campanha',
            fields=[
                ('id_campanha', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_inicio', models.DateField(blank=True, null=True)),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('publico_alvo', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('ativa', 'Ativa'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='planejada', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id_hospital', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='PontoColeta',
            fields=[
                ('id_ponto', models.BigAutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.endereco')),
            ],
        ),
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id_doacao', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_doacao', models.DateField()),
                ('amostra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.amostrasangue')),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campanha')),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doador')),
                ('ponto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pontocoleta')),
            ],
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id_agendamento', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_agendada', models.DateField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('cancelado', 'Cancelado'), ('realizado', 'Realizado'), ('expirado', 'Expirado')], default='agendado', max_length=20)),
                ('doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.doador')),
                ('campanha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.campanha')),
                ('ponto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.pontocoleta')),
            ],
        ),
        migrations.CreateModel(
            name='CampanhaColaborador',
            fields=[
                ('id_campanha_colaborador', models.BigAutoField(primary_key=True, serialize=False)),
                ('funcao', models.CharField(blank=True, max_length=50, null=True)),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campanha')),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.colaborador')),
            ],
            options={
                'verbose_name': 'Colaborador da Campanha',
                'verbose_name_plural': 'Colaboradores de Campanhas',
                'db_table': 'campanha_colaborador',
                'unique_together': {('campanha', 'colaborador')},
            },
        ),
        migrations.CreateModel(
            name='PontoCampanha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campanha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campanha')),
                ('ponto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pontocoleta')),
            ],
            options={
                'unique_together': {('ponto', 'campanha')},
            },
        ),
    ]
